### ISSUE TITLE
Change KEKS link/logo to IBIS

### ISSUE THREAD

**Issue by mukrop** [zverinec/intersob-web#5]
http://ibis.sci.muni.cz/

**Comment by malinajan** [comment]
Do you have IBIS logo in svg? I would use it in KSI.

**Comment by mukrop** [comment]
No, I don't (and I haven't even asked yet).
If you get it, let me know.
Thinking of it, you could also update the logo of Brkos (not too much change but some yes).

**Comment by wormsik** [comment]
update also KSI logo

**Comment by mukrop** [comment]
KSI logo is now available in vector at zverinec gDrive/Grafika/loga-aktivity-zverinca

**Comment by malinajan** [comment]
Why do you want to update KSI logo?

**Comment by mukrop** [comment]
Side-question (that I came to yesterday): Is KSI logo still the Ksi symbol, or is it Karlik (possibly with orange background) as in header of https://ksi.fi.muni.cz/ ?

**Comment by malinajan** [comment]
I have just been discussing the logo with Heňo, the conclusion is *Karlík is the logo*. As Martin says it is available at gDrive.
